RandomForestClassifier:
  n_estimators : 200
  min_samples_split : 5
  min_samples_leaf : 1
  max_samples : null
  max_features : sqrt
  max_depth : 50
  criterion : gini
  class_weight : balanced_subsample
  bootstrap : False