COLUMNS:
  customerID: string
  gender: string
  SeniorCitizen: int
  Partner: string
  Dependents: string
  tenure: int
  PhoneService: string
  MultipleLines: string
  InternetService: string
  OnlineSecurity: string
  OnlineBackup: string
  DeviceProtection: string
  TechSupport: string
  StreamingTV: string
  StreamingMovies: string
  Contract: string
  PaperlessBilling: string
  PaymentMethod: string
  MonthlyCharges: float
  TotalCharges: float
  Churn: int


TARGET_COLUMN:
  name: Churn


num_cols:
  - tenure
  - MonthlyCharges
  - TotalCharges
  - SeniorCitizen

cat_cols:
  - gender
  - Partner
  - Dependents
  - PhoneService
  - MultipleLines
  - InternetService
  - OnlineSecurity
  - OnlineBackup
  - DeviceProtection
  - TechSupport
  - StreamingTV
  - StreamingMovies
  - Contract
  - PaperlessBilling
  - PaymentMethod

columns_to_drop:
  - customerID
