artifacts_roots: artifacts

data_ingestion:
  root_dir:artifacts/data_ingestion
  source_dir: https://github.com/JavithNaseem-J/ML-Project/raw/refs/heads/main/archive.zip
  load_data: artifacts/data_ingestion/data.csv
  unzip_dir: artifacts/data_ingestion